name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Descargando repo
      - name: Instalar Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v3
        name: Instalando gradle
      - name: Compilando ando
        run: ./gradlew build
      - name: Dependency Check
        run: |
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.2.0/dependency-check-12.2.0-release.zip
          unzip dependency-check-12.2.0-release.zip
          dependency-check/bin/dependency-check.sh \
            --scan . \
            --failOnCVSS 7
      - name: Build + Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew build sonarqube \
            -Dsonar.projectKey=demo \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=$SONAR_TOKEN
      
